### ISSUE TITLE
Feature Request or Question - support environment variable

### ISSUE THREAD

**Issue by sasezaki** [ray-di/Ray.Compiler#107]
Hi. Is there any way to support environment variable at runtime ?

Currently, BEAR.Sunday tutorial too refers PHP's `getenv()` function.

https://bearsunday.github.io/manuals/1.0/en/tutorial2.html
```php
            new AuraSqlModule(
                (string) getenv('TKT_DB_DSN'),
```
But it is evaluated (compiled) at build system's environment value.

eg. I use Google Cloud Build for build (Docker container build & di compiled), and run application at Cloud Run.

Is there any way like PHP-DI 's env variable evaluation?
https://php-di.org/doc/php-definitions.html#environment-variables

**Comment by koriym** [comment]
If you want to bind AuraSql connection settings to runtime environment variable values rather than compile-time values, there is a dedicated module for that, [AuraSqlEnvModule](https://github.com/ray-di/Ray.AuraSqlModule?tab=readme-ov-file#module-install).

```php
 $this->install(
    new AuraSqlEnvModule(
        'PDO_DSN',             // getenv('PDO_DSN')
        'PDO_USER',            // getenv('PDO_USER')
        'PDO_PASSWORD',        // getenv('PDO_PASSWORD')
        'PDO_SLAVE'            // getenv('PDO_SLAVE')
        $options,              // optional key=>value array of driver-specific connection options
        $queries               // Queries to execute after the connection.
);
```

> Is there any way like PHP-DI 's env variable evaluation?

There is no way to directly specify an env value that way. Instead, you can [bind to a provider ](https://ray-di.github.io/manuals/1.0/en/provider_bindings.html)that gets its value from an environment variable.

See also https://github.com/ray-di/Ray.AuraSqlModule/issues/67
